version: '3.7'
services:
  app:
    build:
      context: ..
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6.1
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

volumes:
  mongodb_data_container: